export const AUTH_USER = 'AUTH_USER';
export const UNAUTH_USER = 'UNAUTH_USER';
export const AUTH_ERROR = 'AUTH_ERROR';
export const AUTH_LOADING = 'AUTH_LOADING';
export const AUTH_LOADED = 'AUTH_LOADED';

export const GET_USER_DATA = 'GET_USER_DATA';
export const LOADING_USER_DATA = 'LOADING_USER_DATA';
export const LOADED_USER_DATA = 'LOADED_USER_DATA';
export const GET_USER_DATA_ERROR = 'GET_USER_DATA_ERROR';
export const LOADED_FIRST_USER_DATA = 'LOADED_FIRST_USER_DATA';

export const ACTIVATE_LEFT_PANEL = 'ACTIVATE_LEFT_PANEL';
export const DEACTIVATE_LEFT_PANEL = 'DEACTIVATE_LEFT_PANEL';
export const ACTIVATE_RIGHT_PANEL = 'ACTIVATE_RIGHT_PANEL';
export const DEACTIVATE_RIGHT_PANEL = 'DEACTIVATE_RIGHT_PANEL';

export const ACTIVATE_SELECTED_USER_CONTROL = 'ACTIVATE_SELECTED_USER_CONTROL';
export const DEACTIVATE_SELECTED_USER_CONTROL = 'DEACTIVATE_SELECTED_USER_CONTROL';
export const SET_SELECTED_USER = 'SET_SELECTED_USER';
export const DELETE_SELECTED_USER = 'DELETE_SELECTED_USER';
