export const AUTH_USER = 'AUTH_USER';
export const UNAUTH_USER = 'UNAUTH_USER';
export const AUTH_ERROR = 'AUTH_ERROR';
export const GET_USER_DATA = 'GET_USER_DATA';
export const LOADING_USER_DATA = 'LOADING_USER_DATA';
export const LOADED_USER_DATA = 'LOADED_USER_DATA';
export const GET_USER_DATA_ERROR = 'GET_USER_DATA_ERROR';
